services:
  - type: web
    name: blogging-platform-api
    env: python
    region: frankfurt
    plan: free
    buildCommand: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
    startCommand: gunicorn --workers=4 --threads=4 --timeout=120 core.wsgi:application
    healthCheckPath: /api/health/
    healthCheckTimeout: 100
    autoDeploy: false
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: DATABASE_URL
        fromDatabase:
          name: blogging-platform-db
          property: connectionString
      - key: DJANGO_SETTINGS_MODULE
        value: core.settings
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: .onrender.com,blogging-platform-api-74bv.onrender.com
      - key: PYTHONPATH
        value: /app
    disk:
      name: blogging-platform-data
      mountPath: /app/data
      sizeGB: 1

  - type: redis
    name: blogging-platform-redis
    ipAllowList: []
    plan: free

databases:
  - name: blogging-platform-db
    databaseName: blogging_platform
    user: blogging_platform_user
    plan: free
    ipAllowList: []
