services:
  - type: web
    name: blogging-platform-api
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
    startCommand: gunicorn core.wsgi:application
    healthCheckPath: /api/health/
    healthCheckTimeout: 300
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: DATABASE_URL
        fromDatabase:
          name: blogging_platform_db
          property: connectionString
      - key: REDIS_URL
        fromService:
          name: blogging-platform-redis
          type: redis
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
      - key: ALLOWED_HOSTS
        value: ".onrender.com"

  - type: redis
    name: blogging-platform-redis
    ipAllowList: []
    plan: free

databases:
  - name: blogging_platform_db
    databaseName: blogging_platform
    user: blogging_platform_user
    plan: free
