services:
  - type: web
    name: blogging-platform-api
    env: python
    buildCommand: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
    startCommand: gunicorn core.wsgi:application --log-file - --log-level debug
    healthCheckPath: /api/health/
    healthCheckTimeout: 60
    autoDeploy: false
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: DATABASE_URL
        fromDatabase:
          name: blogging-platform-db
          property: connectionString
      - key: DJANGO_SETTINGS_MODULE
        value: core.settings
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: .onrender.com,blogging-platform-api-74bv.onrender.com
    plan: free

  - type: redis
    name: blogging-platform-redis
    ipAllowList: []
    plan: free

databases:
  - name: blogging-platform-db
    databaseName: blogging_platform
    user: blogging_platform_user
    plan: free
