services:
  - type: web
    name: blogging-platform-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python manage.py migrate && python manage.py collectstatic --noinput && gunicorn core.wsgi:application
    healthCheckPath: /api/health/
    healthCheckTimeout: 300
    autoDeploy: false
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: DATABASE_URL
        fromDatabase:
          name: blogging-platform-db
          property: connectionString
      - key: DJANGO_SETTINGS_MODULE
        value: core.settings
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: .onrender.com
    initialDeployHook: python manage.py makemigrations

  - type: redis
    name: blogging-platform-redis
    ipAllowList: []
    plan: free

databases:
  - name: blogging-platform-db
    databaseName: blogging_platform
    user: blogging_platform_user
    plan: free
