# Generated by Django 4.2.17 on 2024-12-20 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_rename_posts_post_created_2a1cba_idx_posts_post_created_183a3b_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='posts/images/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='posts/thumbnails/%Y/%m/%d/'),
        ),
    ]
